# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  loantenure:
    image: loantenure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5276:5276
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
