# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  loantenure:
    image: loantenure_v-1.3:Backend-API-Tenure_v-1.3
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5276:5276
    networks:
      default:
        aliases:
          - Tenure.dev

  nodep:
    image: expense-tracker_v-1.3:Frontend-Tenure_V.1.3
    build:
      context: ../nodep
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - ../nodep/.env
    ports:
      - 3000:3000
